
services:
  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/backend
      - REDIS_HOST=redis
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    depends_on:
      - db
      - redis
    command: sh -c "npx prisma migrate dev --name add_submission_model && npm run start:dev"
    volumes:
      - ./api:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  python_runner:
    build:
      context: ./runners/python-runner
      dockerfile: Dockerfile
    image: python-runner:latest

  java_runner:
    build:
      context: ./runners/java-runner
      dockerfile: Dockerfile
    image: java-runner:latest

  node_runner:
    build:
      context: ./runners/node-runner
      dockerfile: Dockerfile
    image: node-runner:latest

  cpp_runner:
    build:
      context: ./runners/cpp-runner
      dockerfile: Dockerfile
    image: cpp-runner:latest

  worker_python:
    build:
      context: ./workers/worker_python
      dockerfile: Dockerfile
    container_name: worker_python
    environment:
      - WORKER_NAME=worker_python
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/backend
      - TIME_LIMIT_MS=5000
    depends_on:
      - redis
      - db
      - python_runner
    command: npm run start:dev
    volumes:
      - ./workers/worker_python:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_sandboxes:/app/.sandbox:rw

  worker_java:
    build:
      context: ./workers/worker_java
      dockerfile: Dockerfile
    container_name: worker_java
    environment:
      - WORKER_NAME=worker_java
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/backend
      - TIME_LIMIT_MS=5000
      - MEMORY_LIMIT_MB=256
    depends_on:
      - redis
      - db
      - java_runner
    command: npm run start:dev
    volumes:
      - ./workers/worker_java:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_sandboxes:/app/.sandbox:rw

  worker_cpp:
    build:
      context: ./workers/worker_c++
      dockerfile: Dockerfile
    container_name: worker_cpp
    environment:
      - WORKER_NAME=worker_cpp
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/backend
      - TIME_LIMIT_MS=5000
      - MEMORY_LIMIT_MB=256
    depends_on:
      - redis
      - db
      - cpp_runner
    command: npm run start:dev
    volumes:
      - ./workers/worker_c++:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_sandboxes:/app/.sandbox:rw

  worker_node:
    build:
      context: ./workers/worker_node
      dockerfile: Dockerfile
    container_name: worker_node
    environment:
      - WORKER_NAME=worker_node
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/backend
      - TIME_LIMIT_MS=5000
      - MEMORY_LIMIT_MB=256
    depends_on:
      - redis
      - db
      - node_runner
    command: npm run start:dev
    volumes:
      - ./workers/worker_node:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_sandboxes:/app/.sandbox:rw

volumes:
  postgres_data:
  redis_data:
  runner_sandboxes:
