apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-node-scaler
  namespace: runners
spec:
  scaleTargetRef:
    name: worker-node
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: redis
    metadata:
      address: 172.20.0.2:6379
      listName: bull:submissions-node:wait
      listLength: "5"
      activationListLength: "10"

