apiVersion: v1
kind: Secret
metadata:
  name: worker-secrets
  namespace: runners
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@172.19.0.2:5432/backend
  TIME_LIMIT_MS: "5000"
  MEMORY_LIMIT_MB: "256"

