FROM node:20-bullseye

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential g++ time \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json* tsconfig.json ./

RUN npm install

COPY src ./src

RUN npm run build

CMD ["node", "dist/main.js"]
