export enum ChallengeStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum Difficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export class Challenge {
  constructor(
    public readonly id: string,
    public title: string,
    public description: string,
    public difficulty: Difficulty,
    public tags: string[],
    public timeLimit: number, // in milliseconds
    public memoryLimit: number, // in MB
    public status: ChallengeStatus,
    public readonly createdAt: Date,
    public updatedAt: Date,
  ) {}

  static create(
    title: string,
    description: string,
    difficulty: Difficulty,
    tags: string[],
    timeLimit: number,
    memoryLimit: number,
  ): Challenge {
    const now = new Date();
    return new Challenge(
      '', // ID will be generated by database
      title,
      description,
      difficulty,
      tags,
      timeLimit,
      memoryLimit,
      ChallengeStatus.DRAFT,
      now,
      now,
    );
  }

  update(
    title?: string,
    description?: string,
    difficulty?: Difficulty,
    tags?: string[],
    timeLimit?: number,
    memoryLimit?: number,
    status?: ChallengeStatus,
  ): Challenge {
    return new Challenge(
      this.id,
      title ?? this.title,
      description ?? this.description,
      difficulty ?? this.difficulty,
      tags ?? this.tags,
      timeLimit ?? this.timeLimit,
      memoryLimit ?? this.memoryLimit,
      status ?? this.status,
      this.createdAt,
      new Date(),
    );
  }

  publish(): Challenge {
    return this.update(undefined, undefined, undefined, undefined, undefined, undefined, ChallengeStatus.PUBLISHED);
  }

  archive(): Challenge {
    return this.update(undefined, undefined, undefined, undefined, undefined, undefined, ChallengeStatus.ARCHIVED);
  }

  isPublished(): boolean {
    return this.status === ChallengeStatus.PUBLISHED;
  }

  isDraft(): boolean {
    return this.status === ChallengeStatus.DRAFT;
  }

  isArchived(): boolean {
    return this.status === ChallengeStatus.ARCHIVED;
  }
}