export class TestCase {
  constructor(
    public readonly id: string,
    public readonly challengeId: string,
    public input: string,
    public expectedOutput: string,
    public isHidden: boolean,
    public readonly createdAt: Date,
  ) {}

  static create(
    challengeId: string,
    input: string,
    expectedOutput: string,
    isHidden: boolean = false,
  ): TestCase {
    return new TestCase(
      '', // ID will be generated by database
      challengeId,
      input,
      expectedOutput,
      isHidden,
      new Date(),
    );
  }

  update(input?: string, expectedOutput?: string, isHidden?: boolean): TestCase {
    return new TestCase(
      this.id,
      this.challengeId,
      input ?? this.input,
      expectedOutput ?? this.expectedOutput,
      isHidden ?? this.isHidden,
      this.createdAt,
    );
  }

  hide(): TestCase {
    return this.update(undefined, undefined, true);
  }

  show(): TestCase {
    return this.update(undefined, undefined, false);
  }

  isVisible(): boolean {
    return !this.isHidden;
  }
}