export enum UserRole {
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN',
}

export class User {
  constructor(
    public readonly id: string,
    public email: string,
    public password: string,
    public role: UserRole,
    public readonly createdAt: Date,
    public updatedAt: Date,
  ) {}

  static create(email: string, password: string, role: UserRole = UserRole.STUDENT): User {
    const now = new Date();
    return new User(
      '', // ID will be generated by database
      email,
      password,
      role,
      now,
      now,
    );
  }

  update(email?: string, password?: string, role?: UserRole): User {
    return new User(
      this.id,
      email ?? this.email,
      password ?? this.password,
      role ?? this.role,
      this.createdAt,
      new Date(),
    );
  }

  isAdmin(): boolean {
    return this.role === UserRole.ADMIN;
  }

  isStudent(): boolean {
    return this.role === UserRole.STUDENT;
  }
}